export const ROUTES = {
  home: "/",
  register: "/register",
  movies: "/movies",
  movieDetail: (id) => `/movies/${id}`,
  tv: "/tv",
  browse: "/browse",
  blog: "/blog",
  blogDetail: (id) => `/blog/${id}`,
  comments: "/comments",
  contact: "/contact",
  dmca: "/dmca",
  terms: "/terms",
  faq: "/faq",
  userPanel: "/userpanel",
  dashboard: "/userpanel/dashboard",
  account: "/userpanel/account",
  favorites: "/userpanel/favorite",
  purchases: "/userpanel/buy",
  settings: "/userpanel/setting",
  security: "/userpanel/security",
};
